//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVuelaSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asiento
    {
        public string codigoasiento { get; set; }
        public string vacante { get; set; }
        public decimal codigovuelo { get; set; }
    }
}
