//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVuelaSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservacion()
        {
            this.equipajecheckin = new HashSet<equipajecheckin>();
        }
    
        public decimal codreservacion { get; set; }
        public decimal codvuelo { get; set; }
        public string codasiento { get; set; }
        public string checkin { get; set; }
        public string pasedeabordaje { get; set; }
        public string pasedeabordajeverificacion { get; set; }
        public string codcliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipajecheckin> equipajecheckin { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual vuelo vuelo { get; set; }
    }
}
