//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoVuelaSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vuelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vuelo()
        {
            this.reservacion = new HashSet<reservacion>();
            this.vuelo1 = new HashSet<vuelo>();
            this.vuelo2 = new HashSet<vuelo>();
        }
    
        public decimal idvuelo { get; set; }
        public string aeropuertosalida { get; set; }
        public string aeropuertodestino { get; set; }
        public Nullable<System.DateTime> fechasalida { get; set; }
        public Nullable<System.DateTime> fechallegada { get; set; }
        public Nullable<decimal> precioturista { get; set; }
        public Nullable<decimal> precioejecutiva { get; set; }
        public Nullable<decimal> precioprimeraclase { get; set; }
    
        public virtual aeropuerto aeropuerto { get; set; }
        public virtual aeropuerto aeropuerto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservacion> reservacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vuelo> vuelo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vuelo> vuelo2 { get; set; }
    }
}
